Gbemileke/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from frontend import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('', views.index, name='index'),
    path('pages/', include('frontend.urls')),
    path('user/', include('backend.urls')),
    path('payments/', include("payments.urls")), 
    path('profile/', include("users.urls")), 
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='backend/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='backend/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='backend/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/urls.py
from django.urls import path
from django.conf.urls import url 
from backend import views

app_name = 'backend'

urlpatterns = [  
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('logout_view-page/', views.logout_view, name='logout_view'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('view_gadgets/', views.gadgets, name='gadgets'),
    path('view_gadgets/<int:gadgets_id>', views.edit_gadgets, name='edit_gadgets'),
    path('delete_gadgets/<int:deletegadgets_id>', views.delete_gadgets, name='delete_gadgets'),
    path('view_pastries/', views.pastries, name='pastries'),
    path('view_pastries/<int:pastries_id>', views.edit_pastries, name='edit_pastries'),
    path('delete_pastries/<int:deletepastries_id>', views.delete_pastries, name='delete_pastries'),
    path('view_wears/', views.wears, name='wears'),
    path('upload-gadgets/', views.add_gadgets, name='add_gadgets'),
    path('upload-pastries/', views.add_pastries, name='add_pastries'),
    path('upload-wears/', views.add_wears, name='add_wears'),
    path('view_wears/<int:wears_id>', views.edit_wears, name='edit_wears'),
    path('upload-blog/', views.add_blog, name='add_blog'),
    path('delete-blog/<int:delete_id>', views.delete_blog, name='delete_blog'),
    path('delete-wears/<int:deletewears_id>', views.delete_wears, name='delete_wears'),
    path('list_all_blog/<int:post_id>', views.edit_blog, name='edit_blog'),
    path('view_preview/<int:agent>', views.preview, name='preview'),
    path('subscribers/', views.newsletter, name='newsletter'),
    path('messages/', views.message, name='message'),
    path('reastaurant/', views.food, name='food'),
    path('change-password/', views.change_password, name='change_password'),
    path('view_blog/<int:view_id>', views.view_blog, name='view_blog'),
    path('list_all_blog/', views.list_all_blog, name='list_all_blog'),
     path('change_password/', views.change_password, name='change_password'),
    path('password_reset/', views.password_reset_request, name='password_reset_request'),

]

templates/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from frontend import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from backend.views import activation_sent_view, activate,password_reset_request

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:index_id>/', views.detail_index, name='detail_index'),
    path('pages/', include('frontend.urls')),
    path('backend/', include('backend.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='backend/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='backend/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='backend/password_reset_complete.html'), name='password_reset_complete'),
    path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.conf.urls import url 
from users import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.user_profile, name='user_profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),

]

backend/models.py
from django.db import models

# Create your models here.

backend/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core import mail
from django.views.generic import ListView
from django.contrib.auth import update_session_auth_hash
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView

# Models
from django.contrib import messages
from frontend.models import *
from backend.forms import *
from payments.models import *
from users.models import *
from users.forms import *

# Password Reset
from django.conf import settings
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import BadHeaderError, send_mail
from django.db.models import Q
from django.http import HttpResponse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
 #  end

def login_view(request):
    if request.method == 'POST':
        user_name = request.POST.get('user_name')
        password = request.POST.get('password')

        # Authenticate the user
        user = authenticate(request, username=user_name, password=password)  

        # If the user is authenticated, log them in and redirect to the homepage
        if user is not None:
            login(request, user)
            # if user.account_type == 'admin':
            #     return redirect('backend/user_profile.html')
            # elif user.account_type == 'vendor':
            #     return redirect('backend/user_profile.html')
            # elif user.account_type == 'user':
            #     return redirect('backend/user_profile.html')
            return render(request, 'backend/index.html')
        else:
            messages.error(request, 'Invalid username or password')  
    return render(request, 'frontend/login.html')



def register(request):
    if request.method  == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.user_name = form.cleaned_data.get('user_name')
            user.first_name = form.cleaned_data.get('first_name')
            user.email = form.cleaned_data.get('email')
            user.account_type = form.cleaned_data.get('account_type')
            messages.success(request, 'User Registered, you can can  proceed to Log in page')
    else:
        form = RegisterForm()
    return render(request, 'frontend/reg.html', {'reg':form})

@login_required(login_url='/backend/login/')
def logout_view(request):
    logout(request)
    return redirect('index')

@login_required(login_url='/backend/login/')
def dashboard(request):
    list_all_blog = Blog.objects.filter(user=request.user)[:4]
    return render(request, 'backend/index.html', {'list_blog':list_all_blog})

@login_required(login_url='/backend/login/')
def message(request):
    contact = Contact.objects.all()
    return render(request, 'backend/contact.html', {'contact':contact})

@login_required(login_url='/backend/login/')
def newsletter(request):
    newsletter = SubscribeModel.objects.order_by('-timestamp')
    return render(request, 'backend/newsletter.html', {'newsletter':newsletter})

@login_required(login_url='/backend/login/')
def change_password(request):
    if request.method == 'POST':
        change_password = PasswordChangeForm(data=request.POST,
        user=request.user)
        if change_password.is_valid():
            change_password.save()
            update_session_auth_hash(request, change_password.user)
            messages.success(request, 'Password changed successfully.')
    else:
        change_password = PasswordChangeForm(user=request.user)
    return render(request, 'backend/change_password.html', {'pass_key':change_password})


def password_reset_request(request):
    if request.method == "POST":
        domain = request.headers['Host']
        password_reset_form = PasswordReset(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            # You can use more than one way like this for resetting the password.
            # ...filter(Q(email=data) | Q(username=data))
            # but with this you may need to change the password_reset form as well.
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "backend/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000/',
                        'site_name':'ALLINONE',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'josepholuwagbemi02@gmail.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordReset()
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Upload successfully.')
            return redirect('frontend:password_reset_request')
    else:
        subscribe_form = SubscribeForm()
    return render(request=request, template_name="backend/password_reset.html",
                  context={"password_reset_form": password_reset_form,'subscribe_form':subscribe_form})

@login_required(login_url='/backend/login/')
def food(request):
    restaurant = Restaurant.objects.order_by('-date')
    return render(request, 'backend/food.html', {'restaurant':restaurant})

@login_required(login_url='/backend/login/')
def pastries(request):
    pastries = Pastries.objects.order_by('-date')
    return render(request, 'backend/pastries.html', {'pastries':pastries})

@login_required(login_url='/backend/login/')
def edit_pastries(request, pastries_id):
    pastries_post = get_object_or_404(Pastries, id=pastries_id)
    if request.method == 'POST':
        editpastries_form = EditPastriesForm(request.POST, request.FILES,instance=pastries_post)
        if editpastries_form.is_valid():
            editpastries_form = editpastries_form.save(commit=False)
            editpastries_form.user = request.user
            editpastries_form.save()
            messages.success(request, 'Successfully Edited.')
            editpastries_form = EditPastriesForm(instance=pastries_post)
            
    else:
        editpastries_form = EditPastriesForm(instance=pastries_post)
    return render(request, 'backend/edit_cakes.html', {'editpastries_form': editpastries_form})

@login_required(login_url='/backend/login/')
def delete_pastries(request, deletepastries_id):
    pastries_record = get_object_or_404(Pastries, id=deletepastries_id)
    pastries_record.delete()
    return redirect('backend:dashboard')

@login_required(login_url='/backend/login/')
def gadgets(request):
    gadgets = Gadgets.objects.order_by('-date')
    return render(request, 'backend/gadgets.html', {'gadgets':gadgets})

@login_required(login_url='/backend/login/')
def edit_gadgets(request, gadgets_id):
    gadgets_post = get_object_or_404(Gadgets, id=gadgets_id)
    if request.method == 'POST':
        editgadgets_form = EditGadgetsForm(request.POST, request.FILES,instance=gadgets_post)
        if editgadgets_form.is_valid():
            editgadgets_form = editgadgets_form.save(commit=False)
            editgadgets_form.user = request.user
            editgadgets_form.save()
            messages.success(request, 'Successfully Edited.')
            editgadgets_form = EditGadgetsForm(instance=gadgets_post)
            
    else:
        editgadgets_form = EditGadgetsForm(instance=gadgets_post)
    return render(request, 'backend/edit_phone.html', {'editgadgets_form': editgadgets_form})

@login_required(login_url='/backend/login/')
def delete_gadgets(request, deletegadgets_id):
    gadgets_record = get_object_or_404(Gadgets, id=deletegadgets_id)
    gadgets_record.delete()
    return redirect('backend:dashboard')


@login_required(login_url='/backend/login/')
def wears(request):
    wears = Fashion.objects.order_by('-date')
    return render(request, 'backend/wears.html', {'wears':wears})

@login_required(login_url='/backend/login/')
def add_gadgets(request):
    if request.method == 'POST':
        gadgets_form = GadgetsForm(request.POST, request.FILES)
        if gadgets_form.is_valid():
            gadgets_form = gadgets_form.save(commit=False)
            gadgets_form.user = request.user
            gadgets_form.save()
            messages.success(request, 'Upload successfully.')
            return redirect('backend:add_gadgets')
    else:
        gadgets_form = GadgetsForm()
    return render(request, 'backend/add_phone.html', {'gadgets_form': gadgets_form})


@login_required(login_url='/backend/login/')
def add_pastries(request):
    if request.method == 'POST':
        pastries_form = PastriesForm(request.POST, request.FILES)
        if pastries_form.is_valid():

templates/backend/admin_sidebar.html
{% load static %}
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
      <a href="{% url 'index' %}" class="app-brand-link">
        <img src="{% static 'frontend/assets/img/shopcityfav.png' %}" data-retina="true" alt="" width="40" height="40" style="border-radius: 30px;" >&nbsp; &nbsp;</a>
        <h1 class="logo me-auto"><a href="{% url 'index' %}" ><img src="{% static 'frontend/assets/img/logo.png' %} " style="width: 130px !important;"></a></h1>
      </a>

      <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
        <i class="bx bx-chevron-left bx-sm align-middle"></i>
      </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
      <!-- Dashboard -->
      <li class="menu-item active">
        <a href="{% url 'backend:dashboard' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-home-circle"></i>
          <div data-i18n="Analytics">Dashboard</div>
        </a>
      </li>

      <li class="menu-header small text-uppercase">
        <span class="menu-header-text">Pages</span>
      </li>
      <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle">
          <i class="menu-icon tf-icons bx bx-cube-alt"></i>
          <div data-i18n="Misc">Blogs</div>
        </a>
        <ul class="menu-sub">
          <li class="menu-item">
            <a href="{% url 'backend:add_blog' %}" class="menu-link">
              <div data-i18n="Error">Upload</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'backend:list_all_blog' %}" class="menu-link">
              <div data-i18n="Error">View</div>
            </a>
          </li>
        </ul>
      </li>
      <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle">
          <i class="menu-icon tf-icons bx bx-chat"></i>
          <div data-i18n="Contact">Services</div>
        </a>
        <ul class="menu-sub">
          <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
              <i class="menu-icon tf-icons bx bx-tshirt"></i>
              <div data-i18n="Misc">Fashion</div>
            </a>
            <ul class="menu-sub">
              <li class="menu-item">
                <a href="{% url 'backend:add_wears' %}" class="menu-link">
                  <div data-i18n="Error">Upload</div>
                </a>
              </li>
              <li class="menu-item">
                <a href="{% url 'backend:wears' %}" class="menu-link">
                  <div data-i18n="Error">View</div>
                </a>
              </li>
            </ul>
          </li>
          <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
              <i class="menu-icon tf-icons bx bx-tshirt"></i>
              <div data-i18n="Misc">Pastries</div>
            </a>
            <ul class="menu-sub">
              <li class="menu-item">
                <a href="{% url 'backend:add_pastries' %}" class="menu-link">
                  <div data-i18n="Error">Upload</div>
                </a>
              </li>
              <li class="menu-item">
                <a href="{% url 'backend:pastries' %}" class="menu-link">
                  <div data-i18n="Error">View</div>
                </a>
              </li>
            </ul>
          </li>
          <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
              <i class="menu-icon tf-icons bx bx-mug-saucer"></i>
              <div data-i18n="Misc">Restaurants</div>
            </a>
            <ul class="menu-sub">
              <li class="menu-item">
                <a href="{% url 'backend:add_blog' %}" class="menu-link">
                  <div data-i18n="Error">Upload</div>
                </a>
              </li>
              <li class="menu-item">
                <a href="{% url 'backend:food' %}" class="menu-link">
                  <div data-i18n="Error">View</div>
                </a>
              </li>
            </ul>
          </li>
          <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
              <i class="menu-icon tf-icons bx bx-tshirt"></i>
              <div data-i18n="Misc">Gadgets</div>
            </a>
            <ul class="menu-sub">
              <li class="menu-item">
                <a href="{% url 'backend:add_gadgets' %}" class="menu-link">
                  <div data-i18n="Error">Upload</div>
                </a>
              </li>
              <li class="menu-item">
                <a href="{% url 'backend:gadgets' %}" class="menu-link">
                  <div data-i18n="Error">View</div>
                </a>
              </li>
            </ul>
          </li>
          <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
              <i class="menu-icon tf-icons bx bx-tshirt"></i>
              <div data-i18n="Misc">Hostels</div>
            </a>
            <ul class="menu-sub">
              <li class="menu-item">
                <a href="{% url 'backend:add_blog' %}" class="menu-link">
                  <div data-i18n="Error">Upload</div>
                </a>
              </li>
              <li class="menu-item">
                <a href="{% url 'backend:list_all_blog' %}" class="menu-link">
                  <div data-i18n="Error">View</div>
                </a>
              </li>
            </ul>
          </li>
          
        </ul>
      </li>

      <li class="menu-item">
        <a href="{% url 'backend:message' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-chat"></i>
          <div data-i18n="Contact">Messages</div>
        </a>
      </li>
      <!-- Components -->
      <li class="menu-header small text-uppercase"><span class="menu-header-text">Account Settings</span></li>
      <!-- Cards -->
      <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle">
          <i class="menu-icon tf-icons bx bx-dock-top"></i>
          <div data-i18n="Account Settings">Account Settings</div>
        </a>
        <ul class="menu-sub">
          <li class="menu-item">
            <a href="{% url 'users:user_profile' %}" class="menu-link">
              <div data-i18n="Account"user_profile>User Profile</div>
            </a>
          </li>
          <!-- <li class="menu-item">
            <a href="#" class="menu-link">
              <div data-i18n="Notifications">Notifications</div>
            </a>
          </li> -->
          <li class="menu-item">
            <a href="{% url 'users:edit_profile' %}" class="menu-link">
              <div data-i18n="Edit Account">Edit Account</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'backend:password_reset_request' %}" class="menu-link" target="_blank">
              <div data-i18n="Basic">Password Reset</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'backend:change_password' %}" class="menu-link" target="_blank">
              <div data-i18n="Basic">Change Password</div>
            </a>
          </li>
        </ul>
      </li>
      <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle">
          <i class="menu-icon tf-icons bx bx-wallet-alt"></i>
          <div data-i18n="Authentications">Wallets</div>
        </a>
        <ul class="menu-sub">
          
        </ul>
      </li>

      <!-- Forms & Tables -->
      <li class="menu-header small text-uppercase"><span class="menu-header-text">Newsletter &amp; Comments</span></li>
      <!-- Forms -->
      <li class="menu-item">
        <a href="{% url 'backend:newsletter' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-detail"></i>
          <div data-i18n="Newsletter">Newsletter</div>
        </a> 
      </li>
      
      <!-- Tables -->
      <li class="menu-item">
        <a href="#" class="menu-link">
          <i class="menu-icon tf-icons bx bx-chat"></i>
          <div data-i18n="Comments">Comments</div>
        </a>
      </li>
      <!-- Misc -->
    </ul>
</aside>

<!-- Layout container -->
<div class="layout-page">
  <!-- Navbar -->

  <nav
    class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
    id="layout-navbar"
  >
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
      <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
        <i class="bx bx-menu bx-sm"></i>
      </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
    

      <ul class="navbar-nav flex-row align-items-center ms-auto">
        <!-- Place this tag where you want the button to render. -->
        <li class="nav-item lh-1 me-3">
          <a
            class="github-button"
            href="#"
            data-icon="octicon-star"
            data-size="large"
            data-show-count="true"
            aria-label="Star themeselection/sneat-html-admin-template-free on GitHub"
            >{{user.user_name }}</a
          >
        </li>

        <!-- User -->
        <li class="nav-item navbar-dropdown dropdown-user dropdown">
          <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
            <div class="avatar avatar-online">
              <i class="fa fa-profile"></i>
              <img class="img-profile rounded-circle" src="{{ user.image_url}}">
            </div>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li>
              <a class="dropdown-item" href="#">
                <div class="d-flex">
                  <div class="flex-shrink-0 me-3">
                    <div class="avatar avatar-online">
                      <img class="img-profile rounded-circle" src="{{ user.image_url}}">
                    </div>
                  </div>
                  <div class="flex-grow-1">
                    <span class="fw-semibold d-block">{{user.user_name }}</span>
                    <small class="text-muted">Admin</small>
                  </div>
                </div>
              </a>
            </li>
            <li>
              <div class="dropdown-divider"></div>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'users:user_profile' %}">
                <i class="bx bx-user me-2"></i>
                <span class="align-middle">My Profile</span>
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'backend:change_password' %}">
                <i class="bx bx-cog me-2"></i>
                <span class="align-middle">Password Settings</span>
              </a>
            </li>
            <li>
              <div class="dropdown-divider"></div>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'backend:logout_view' %}" id="warning">
                <i class="bx bx-power-off me-2"></i>
                <span class="align-middle">Log Out</span>
              </a>
            </li>
          </ul>
        </li>
        <!--/ User -->
      </ul>
    </div>
  </nav>

templates/backend/change_password.html
{% extends 'backend/base.html' %}
{% load static %}
<!Doctype html>
{% block title %}
shopcitymall
{% endblock %}

{% block content %}
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Account Authentication /</span>Change Password</h4>

              <div class="row">
                <div class="col-md-12 box_general padding_bottom" style="font-family: Georgia, 'Times New Roman', Times, serif; font-style: oblique;">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-success">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                    
                    <form method="post" >
                        {% csrf_token %}
                        {{ pass_key.as_p }}
                            <input type="submit" value="Change Password" class="btn btn-success">
                    </form>
                </div>
              </div>
            </div>
            <!-- / Content -->

  {% endblock %}

templates/backend/password_reset_complete.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title%}
shopcitymall
{% endblock %}

{% block content %}

    <!-- ##### Catagory Featured Area Start ##### -->
    <div class="catagory-featured-post bg-overlay clearfix" style="background-image: url({% static 'frontend/img/bg-img/23.jpg' %})">
        <div class="container-fluid h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12 col-lg-9">
					<div class="col-md-12 animate-box">
						<h1 style="color: #ffff !important;"><span class="colored">Password</span>Reset Complete</h1>
					</div>
                </div>
            </div>
        </div>
    </div>

		<div id="best-deal">
			<div class="container">
					<h2 class="font-weight-bold mt-3">Password reset complete</h2>	
					<hr>
					<p>
						Your password has been set. You can go ahead and log in now.
					</p>
					<a href="{% url 'backend:login_view' %}" class="btn btn-primary">Log in </a>
			</div>
		</div>


{% endblock%}

templates/backend/preview.html
{% extends 'backend/base.html' %}
{% load static %}
<!Doctype html>
{% block title %}
shopcitymall
{% endblock %}

{% block content %}

          <!-- / Navbar -->

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Blogs /</span> Edit Blogs</h4>
              <div class="list_general" style="font-family: Georgia, 'Times New Roman', Times, serif; font-style: oblique;">
                <div class="row">
                    <div class="col-lg-8">
                        <section id="description">
                            <div class="item-block animate-box" data-animate-effect="fadeIn">
                                <div class="">
                                  <figure>
                                    <img src="{{ post.blog_img.url }}" class="img-responsive col-sm-12" style="padding-bottom: 10px; width: 300px; height: 400px; font-family: Georgia, 'Times New Roman', Times, serif; font-style: oblique;">
                                    
                                  </figure>
                                  <div class="fh5co-property-innter">
                                    <h2><a href="#">{{ post.blog_title }}</a></h2>
                                  
                                    <p>{{ post.agent_desription }}</p>
                                     <p><i class="fa fa-phone" style="color: blue !important;"></i>&nbsp;Description:&nbsp; {{ post.blog_description }}</p>
                                     <p><i class="fa fa-map" style="color: blue !important;">&nbsp;</i>Date</i>:&nbsp; {{ post.blog_date }}</p>
                                  </div>
                                   
                                </div>
                              </div>
                        </section>
                    </div>
                </div>
            
            </div>
            <p class=" col-3 mt-3" style="padding-bottom: 40px;"><a href="{%url 'backend:list_all_blog'%}"  class="btn_1 align-items-center p-3" style="border-radius: 20px; background-color: #0d6efd; color: aliceblue;"> Back</a></p>
            </div>
            
            <!-- / Content -->

  {% endblock %}