Gbemileke/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from frontend import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('', views.index, name='index'),
    path('pages/', include('frontend.urls')),
    path('user/', include('backend.urls')),
    path('payments/', include("payments.urls")), 
    path('profile/', include("users.urls")), 
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='backend/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='backend/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='backend/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/urls.py
from django.urls import path
from django.conf.urls import url 
from backend import views

app_name = 'backend'

urlpatterns = [  
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('logout_view-page/', views.logout_view, name='logout_view'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('view_gadgets/', views.gadgets, name='gadgets'),
    path('view_gadgets/<int:gadgets_id>', views.edit_gadgets, name='edit_gadgets'),
    path('delete_gadgets/<int:deletegadgets_id>', views.delete_gadgets, name='delete_gadgets'),
    path('view_pastries/', views.pastries, name='pastries'),
    path('view_pastries/<int:pastries_id>', views.edit_pastries, name='edit_pastries'),
    path('delete_pastries/<int:deletepastries_id>', views.delete_pastries, name='delete_pastries'),
    path('view_wears/', views.wears, name='wears'),
    path('upload-gadgets/', views.add_gadgets, name='add_gadgets'),
    path('upload-pastries/', views.add_pastries, name='add_pastries'),
    path('upload-wears/', views.add_wears, name='add_wears'),
    path('view_wears/<int:wears_id>', views.edit_wears, name='edit_wears'),
    path('upload-blog/', views.add_blog, name='add_blog'),
    path('delete-blog/<int:delete_id>', views.delete_blog, name='delete_blog'),
    path('delete-wears/<int:deletewears_id>', views.delete_wears, name='delete_wears'),
    path('list_all_blog/<int:post_id>', views.edit_blog, name='edit_blog'),
    path('view_preview/<int:agent>', views.preview, name='preview'),
    path('subscribers/', views.newsletter, name='newsletter'),
    path('messages/', views.message, name='message'),
    path('reastaurant/', views.food, name='food'),
    path('change-password/', views.change_password, name='change_password'),
    path('view_blog/<int:view_id>', views.view_blog, name='view_blog'),
    path('list_all_blog/', views.list_all_blog, name='list_all_blog'),
     path('change_password/', views.change_password, name='change_password'),
    path('password_reset/', views.password_reset_request, name='password_reset_request'),

]

frontend/urls.py
from django.urls import path
from django.conf.urls import url 
from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('', views.about, name='about'),
    path('restaurant/', views.foods, name='foods'),
    path('wears/', views.wears, name='wears'),
    path('make-payment/', views.payment, name='payment'),
    path('wears_detail/<int:wears_id>/', views.wears_details, name='wears_details'),
    path('phones/', views.phones, name='phones'),
    path('cakes/', views.cakes, name='cakes'),
    path('pastries_detail/<int:cake_id>/', views.cake_details, name='cake_details'),
    path('gadgets_detail/<int:phones_id>/', views.phone_details, name='phone_details'),
    path('blog/', views.blog, name='blog'),
    path('hostel/', views.hostel, name='hostel'),
    path('contact/', views.contact, name='contact'),
    path('detail/<int:detail_id>/', views.blog_details, name='blog_details'), 

]

payments/urls.py
from django.urls import path
from django.conf.urls import url 
from payments import views

app_name = 'payments'

urlpatterns= [
    path('initiate-payment/', views.initiate_payment, name='initiate_payment'),
    path('initiate-payment/<str:ref>/', views.verify_payment, name='verify_payment'),

]

users/urls.py
from django.urls import path
from django.conf.urls import url 
from users import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.user_profile, name='user_profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),

]

payments/models.py
from django.db import models
from django.utils import timezone
import secrets
from .paystack import Paystack
from users.models import *
# Create your models here.

class UserWallet(models.Model):
    user = models.OneToOneField(NewUser, null=True, on_delete=models.CASCADE)
    currency = models.CharField(max_length=50, default='NGN')
    created_at = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self): 
        return self.user.__str__()
    
class Payment(models.Model):
    user = models.ForeignKey(NewUser, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.PositiveIntegerField()
    ref = models.CharField(max_length=200)
    email = models.EmailField()
    verified = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return f"Payment: {self.amount}"
    
    def save(self, *args, **kwargs) -> None:
        while not self.ref:
            ref = secrets.token_urlsafe(50)
            object_with_similar_ref = Payment.objects.filter(ref=ref)
            if not object_with_similar_ref:
                self.ref = ref
        super().save(*args, **kwargs)

    def amount_value(self):
            return int(self.amount) * 100
    
    def verify_payment(self):
        paystack = Paystack()
        status, result = paystack.verify_payment(self.ref, self.amount)
        if status:
            if result['amount'] / 100 == self.amount:
                self.verified = True
            self.save()
        if self.verified:
            return True
        return False
    

frontend/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.views.generic import ListView

# from Olamide.frontend.models import *
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from frontend.models import *
from backend.forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# for sending mail import
from django.conf import settings
from django.core import mail
from django.template.loader import render_to_string
from django.contrib import messages
from django.utils.html import strip_tags
# end

# Create your views here.

def index(request):
    blogs = Blog.objects.order_by('-blog_date')[:6]
    restaurant = Restaurant.objects.order_by('-date')[:4]
    fashion = Fashion.objects.order_by('-date')[:4] 
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('index')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/index.html', {'wears':fashion,'blog':blogs, 'restaurant':restaurant, 'subscribe_form':subscribe_form})


def about(request):
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:about')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/about.html', {'subscribe_form':subscribe_form})

def foods(request):
    restaurant = Restaurant.objects.order_by('-date')
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:foods')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/foods.html', {'restaurant':restaurant,'subscribe_form':subscribe_form})

def phones(request):
    gadgets=Gadgets.objects.order_by('-date')
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:phones')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/phones.html', {'gad':gadgets,'subscribe_form':subscribe_form})

def phone_details(request, phones_id):
    phone_detail =Gadgets.objects.get(id=phones_id)
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:wears')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/phone_details.html', {'det':phone_detail, 'subscribe_form':subscribe_form})

def wears(request):
    fashion = Fashion.objects.order_by('-date')
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:wears')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/wears.html', {'wears':fashion,'subscribe_form':subscribe_form})

def wears_details(request, wears_id):
    wears_detail =Fashion.objects.get(id=wears_id)
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:wears')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/wears_details.html', {'det':wears_detail, 'subscribe_form':subscribe_form})

def cakes(request):
    pastries=Pastries.objects.order_by('-date')
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:cakes')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/cakes.html', {'cake':pastries,'subscribe_form':subscribe_form})

def cake_details(request, cake_id):
    cake_detail =Pastries.objects.get(id=cake_id)
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:wears')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/cake_details.html', {'det':cake_detail, 'subscribe_form':subscribe_form})


def contact(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if  contact_form.is_valid():
            contact_form = contact_form.save(commit=False)
            contact_form.user = request.user
            contact_form.save()
            messages.success(request, 'Your message has been sent. Thank you!')
            return redirect('frontend:contact')
    else:
        contact_form =ContactForm()
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:contact')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/contact.html', {'cont':contact_form,'subscribe_form':subscribe_form})

def blog(request):
    blogs = Blog.objects.order_by('-blog_date')[:6]
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:blog')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/blog.html', {'blog':blogs, 'subscribe_form':subscribe_form})

def blog_details(request, detail_id):
    detail =Blog.objects.get(id=detail_id)
    return render(request, 'frontend/blog_details.html', {'det':detail})

def hostel(request):
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:hostel')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'frontend/hostel.html', {'subscribe_form':subscribe_form})


def payment(request):
    return render(request, 'frontend/payment.html')

payments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from payments.models import *
from frontend.models import *
from payments.forms import *
from backend.forms import *
from django.contrib import messages
from django.conf import settings

# Create your views here.

def initiate_payment(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        payment_form = PaymentForm(request.POST)
        if payment_form.is_valid():
            payment = payment_form.save()
            return render(request, 'backend/make_payment.html', {'payment':payment, 'paystack_public_key':settings.PAYSTACK_PUBLIC_KEY})
    else:
        payment_form = PaymentForm()

    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:phones')
    else:
        subscribe_form = SubscribeForm()
    return render(request, 'backend/initiate_payment.html', {'payment_form':payment_form,'subscribe_form':subscribe_form})
  
def verify_payment(request: HttpRequest, ref: str) -> HttpResponse:
    payment =get_object_or_404(Payment, ref=ref)
    verified = payment.verify_payment()
    if verified:
        messages.success(request, "verification Successful")
    else:
        messages.error(request, "verification Failed")
    
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form = subscribe_form.save(commit=False)
            subscribe_form.user = request.user
            subscribe_form.save()
            messages.success(request, 'Add successfully.')
            return redirect('frontend:phones')
    else:
        subscribe_form = SubscribeForm()
    return redirect('payments:initiate_payment', {'subscribe_form':subscribe_form})

templates/frontend/cake_details.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
    AllInOne.com.ng
{% endblock%}


{% block content %}
    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>Details</h2>
        <p>We're proud to offer vendors the best possible experience on our website. With a wide range of products and services, an easy-to-use interface, advanced security features, and excellent customer support, we're the number one choice for vendors. </p>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Details Section ======= -->
    <section id="course-details" class="course-details">
      <div class="container" data-aos="">

        <div class="row">
          {% if det %}
          
          <div class="col-lg-8">
            
            <div>
              <img src="{{ det.image.url }}" class="img-responsive col-lg-8 col-sm-12 pb-4" >
              
            </div>
            
            
            
            <div class="col-lg-8 col-sm-12" style="padding-left: 20px;">
              <div  style="padding-bottom: 10px; text-align: center;">
              
                <span style="border:solid 1px #1965d8; padding: 10px;">{{ det.date}}</span>
                <span style="border:solid 1px #1965d8; padding: 10px;">Brand:{{ det.vendor_brand }}</span> 
              </div>
              <h3 >{{ det.detail }}</h3>
              <h4>
              &#8358;{{ det.price }}
              </h4>
              
              <!-- <p class="pt-2" style="color: red;">
                available goods: {{det.available_product}}
              </p> -->
              <p class="pt-4">
                + delivery fee &#8358;{{ det.delivery_fee }}
              </p>
              
              <p>
                <!-- SIZE: {{ det.size}} -->
              </p>
              <button type="submit" class="col-4 col-lg-3 mt-4 btn btn-success me-2 col-md-3 col-lg-2"><a href="{% url 'payments:initiate_payment'%}" style="color:#fff; border-radius:15px;">Make Payment</a></button>
              <hr>
            </div>
            
            <button type="submit" class="col-3 col-lg-2 mt-4 btn btn-primary me-2 col-md-3 col-lg-2"><a href="{% url 'frontend:cakes'%}" style="color:#fff;">Back</a></button>
            
          </div>
          
          {% endif %}
          
        </div>

      </div>
    </section><!-- End Cource Details Section -->
 
{% endblock %}

templates/frontend/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'frontend/assets/img/allinone2.png' %}" rel="icon">
    <link href="{% static 'frontend/assets/img/allinone1.jfif' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'frontend/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'frontend/login/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'frontend/login/css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'frontend/login/css/bootstrap.min.css'%}">
    
    <!-- Style -->
    <link rel="stylesheet" href="{% static 'frontend/login/css/style.css' %}">
    <link href="{% static 'frontend/assets/css/style.css' %}" rel="stylesheet">

    <title>Login Page</title>
  </head>
  <body>
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
      <div class="container d-flex align-items-center">

        <h1 class="logo me-auto"><a href="{% url 'index' %}">AllinOne</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="{% url 'index' %}" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar order-last order-lg-0">
          <ul>
            <li><a class="#" href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'frontend:about'%}">About</a></li>
            <li><a href="{% url 'frontend:wears'%}">Wear's</a></li>
            <li><a href="{% url 'frontend:cakes'%}">Pastries</a></li>
            <li><a href="{% url 'frontend:phones'%}">Gadgets</a></li>
            <li><a href="{% url 'frontend:hostel'%}">Hostels</a></li>
            <li><a href="#"><span>Restaurants</span></a>
              <!-- <ul>
                <li><a href="#">Arena</a></li>
                </li>
                <li><a href="#">Krafty</a></li>
                <li><a href="#">Item7</a></li>
                <li><a href="#">Okele Joint</a></li>
                <li><a href="#">Iya Afusat</a></li>
                <li><a href="#">Joy Bliss</a></li>
                <li><a href="#">Joy Bliss</a></li>
              </ul> -->
            </li>
            <li><a href="{% url 'frontend:blog'%}">Blog</a></li>
            <li><a href="{% url 'frontend:contact'%}">Contact</a></li>
          </ul>
          <i class="bi bi-list mobile-nav-toggle" style="padding-left: 160px;"></i>
        </nav><!-- .navbar -->
        <!-- <a href="{% url 'backend:login_view'%}" class="get-started-btn">Register</a> -->
      </div>
    </header><!-- End Header -->
    

    <div class="d-md-flex half">
      <div class="bg" style="background-image: url('{% static 'frontend/login/images/gad2.jpg' %}');"></div>
      <div class="contents">

        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-12">
              <div class="form-block mx-auto">
                <div class="text-center mb-5" style="background-color: #0d6efd; padding: 15px; color: aliceblue">
                <h3><strong>Welcome</strong></h3>
                <!-- <p class="mb-4">Lorem ipsum dolor sit amet elit. Sapiente sit aut eos consectetur adipisicing.</p> -->
                </div>
                <form action="#" method="post">
                  {% if messages %}
                      {% for mes in messages %}
                          <div class="alert {{ mes.tags }}">{{ mes }}</div>
                      {% endfor %}
                  {% endif %}
                  <div class="form-group first">
                    <label for="username">E-mail</label>
                    <input type="user_name" name="user_name" class="form-control" placeholder="your-email@gmail.com" id="username">
                  </div>
                  <div class="form-group last mb-3">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" placeholder="Your Password" id="password">
                  </div>
                  
                  <div class="d-sm-flex mb-5 align-items-center">
                    <label class="control control--checkbox mb-3 mb-sm-0"><span class="caption">Remember me</span>
                      <input type="checkbox" checked="checked"/>
                      <div class="control__indicator"></div>
                    </label> 
                    <span class="ml-auto">
                      <a href="{% url 'backend:password_reset_request' %}" class="forgot-pass" style="text-decoration: none;">
                      Forgot Password</a>
                    </span> 
                    
                  </div>
                  <p>
                        <span>
                            Don't have an account?
                        </span>
                        <b class="pointer">
                            <a href="{% url 'backend:register' %}" style="color: #0d6efd; text-decoration: none;">Create account</a>
                        </b>
                    </p>
                  <input type="submit" value="Log In" class="btn btn-block btn-primary" style="background-color:#0d6efd !important; border-color: #0d6efd;">
                  {% csrf_token %}
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      
    </div>

      <!-- Template Main JS File -->
      
      <script src="{% static 'frontend/login/js/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'frontend/login/js/popper.min.js' %}"></script>
      <script src="{% static 'frontend/login/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'frontend/login/js/main.js' %}"></script>
      <script src="{% static 'frontend/assets/js/main.js' %}"></script>
  </body>
</html>

templates/frontend/wears.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
    AllInOne.com
{% endblock%}


{% block content %}
  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="container">
        <h2>Fashion</h2>
        <p>We're proud to offer vendors the best possible experience on our website. With a wide range of products and services, an easy-to-use interface, advanced security features, and excellent customer support, we're the number one choice for vendors.</p>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Courses Section ======= -->
    <section id="courses" class="courses">
      <div class="container" data-aos="fade-up">

        <div class="row" data-aos="zoom-in" data-aos-delay="100">

          {% if wears %}
                {% for w in wears %}
                <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
                  <div class="course-item">
                
                    <div class="course-content block2">
                      <div class="block2-pic hov-img0">
                        <img src="{{ w.img1.url }}" class="img-fluid" alt="..." style="width: 350px; height: 302px; ">
                        <a href="{% url 'frontend:wears_details' w.id %}" class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 " >
                          More Details
                        </a>
                      </div>
                      
                      <div class="d-flex justify-content-between align-items-center mb-3 block2-txt flex-w flex-t p-t-14 " style="padding: 15px; text-align: center;">
                        <h4 >Brand:{{ w.vendor_brand}}</h4>
                        
                      </div>
                      <div style="text-align: center;">
                        <h3><a href="{% url 'frontend:wears_details' w.id %}">{{ w.product_detail }}</a></h3>
                        <p class="price">&#8358;{{ w.price }}</p>
                      </div>
                      
                      
                      <!-- <p>{{ r.description|truncatewords:30 }}.....</p> -->
                      <div class="trainer d-flex justify-content-between align-items-center">
                      
                        <div class="trainer-rank d-flex align-items-center">
                          <h6 style="color: #1965d8 !important;">ShopCityMall</h6>
                        </div>
                      </div>
                    </div>
                
                  </div>
                </div> <!-- End Course Item-->

                  
                {% endfor %}
              {% endif %} <!-- End Course Item-->

          

        </div>

      </div>
    </section><!-- End Courses Section -->

  </main><!-- End #main -->
  

  <!-- ======= Footer ======= -->
 {% endblock %}